# -*- coding: utf-8 -*-
"""Build La Retraite concept (FR default) from the verified Sasse skeleton."""
import re, base64, sys

SASSE = "sjc-sasse-v2.html"
OUT = "concept-la-retraite-v1.html"
h = open(SASSE, encoding="utf-8").read()

style = h[h.find("<style>")+7 : h.find("</style>")]
script = h[h.rfind("<script>")+8 : h.rfind("</script>")]

# ---- palette remap (Sasse blues -> Retraite royal/amber/cream, their 2026 poster colors)
MAP = {
 "#0F2456":"#0F2456", "#17357F":"#16337E", "#2E4E9E":"#16337E",
 "#BFD0F5":"#F2C879", "#C7D4F5":"#F6E7C8", "#EEF3FC":"#FBF1DC",
 "#F6F8FC":"#FAF3E3", "#DCE3F0":"#E9DCC0", "#131A2A":"#1A2135",
 "#54606F":"#5A6270", "#8C97A8":"#8B93A3",
 "#0A1A3C":"#0B1B3E", "#93A3C4":"#9FB0D8", "#7E93BC":"#8FA0C8",
 "#E3EAF8":"#F6E7C8",
 "rgba(46,78,158,.3)":"rgba(227,154,45,.28)",
 "rgba(201,162,39,.16)":"rgba(227,154,45,.20)",
}
for old, new in MAP.items():
    style = style.replace(old, new)
    script = script.replace(old, new)
style = style.replace(".btn-gold{background:var(--gold);color:#fff}", ".btn-gold{background:var(--gold);color:var(--brand)}")
style = style.replace("border-radius:50%;background:var(--gold);color:#fff", "border-radius:50%;background:var(--gold);color:var(--brand)}")
style = re.sub(r":root\{.*?\}", """:root{
  --brand:#16337E; --brand2:#0F2456; --brand3:#2C4C9E;
  --gold:#E39A2D; --gold-l:#F2C879; --gold-t:#FBF1DC;
  --bg:#FAF3E3; --white:#FFFFFF; --border:#E9DCC0;
  --ink:#1A2135; --slate:#5A6270; --slate-l:#8B93A3;
}""", style, flags=re.S)

# ---- script: school name + WA number (their mobile, from the 2026 poster)
script = script.replace('var WA_NUM = "237677195500"; // the college\'s number (activate WhatsApp Business to make the form live)',
 'var WA_NUM = "237693240047"; // the college\'s mobile (Semaine des Laureats poster, 2026) — WhatsApp Business makes the form live')
script = script.replace('sjc-sasse-v2.html', 'concept-la-retraite-v1.html')
script = script.replace("Bonjour SJC Sasse !", "Bonjour, Collège de la Retraite !")
script = script.replace("Hello SJC Sasse!", "Hello La Retraite College!")

# ---- photo (their Semaine des Laureats 2026 poster, resized)
import PIL.Image as I
im = I.open("assets/retraite-laureats.jpg"); im.thumbnail((900, 900))
im.save("assets/retraite-laureats-s.jpg", quality=80)
B64 = base64.b64encode(open("assets/retraite-laureats-s.jpg","rb").read()).decode()

CREST = ('<svg viewBox="0 0 48 48"><path d="M24 3l17 6v13c0 10.5-7 18-17 23C14 40 7 32.5 7 22V9l17-6z" '
 'fill="#16337E" stroke="#0B1B3E" stroke-width="2"/><path d="M24 10v14M18 16h12" stroke="#FFFFFF" stroke-width="3" '
 'stroke-linecap="round"/><path d="M14 32c4-2.5 7.5-2.5 10 0 2.5-2.5 6-2.5 10 0v7c-4-2.5-7.5-2.5-10 0-2.5-2.5-6-2.5-10 0v-7z" '
 'fill="#FFFFFF"/><path d="M24 32v7" stroke="#16337E" stroke-width="1.3"/></svg>')
CREST_FOOT = ('<svg viewBox="0 0 48 48" width="38" height="38"><path d="M24 3l17 6v13c0 10.5-7 18-17 23C14 40 7 32.5 7 22V9l17-6z" '
 'fill="#0F2456" stroke="#2C4C9E" stroke-width="2"/><path d="M24 10v14M18 16h12" stroke="#2C4C9E" stroke-width="3" '
 'stroke-linecap="round"/><path d="M14 32c4-2.5 7.5-2.5 10 0 2.5-2.5 6-2.5 10 0v7c-4-2.5-7.5-2.5-10 0-2.5-2.5-6-2.5-10 0v-7z" '
 'fill="#FAF3E3"/><path d="M24 32v7" stroke="#0F2456" stroke-width="1.3"/></svg>')

BODY = '''<!-- TOP BAR -->
<div class="topbar"><div class="wrap"><span data-en="Admissions open — 2026/2027 academic year" data-fr="🎓 Inscriptions 2026/2027 — l'administration répond">🎓 Inscriptions 2026/2027 — l'administration répond</span> <span style="display:flex;align-items:center;gap:10px"> <a class="tb-portal" href="#" data-en="E-learning Login →" data-fr="Connexion au portail →">Connexion au portail →</a> <span style="display:flex;border:1px solid var(--brand3);border-radius:99px;overflow:hidden"> <button id="btn-en" onclick="setLang('en')" style="background:transparent;color:#F6E7C8;border:none;font-size:12px;font-weight:800;padding:4px 12px;cursor:pointer">EN</button> <button id="btn-fr" class="on" onclick="setLang('fr')" style="background:var(--gold);color:var(--brand);border:none;font-size:12px;font-weight:800;padding:4px 12px;cursor:pointer">FR</button> </span> <a class="concept-chip" href="#">Maquette de site par <b>AMK</b></a> </span></div></div>
<!-- NAV -->
<header><div class="wrap nav"><a class="logo" href="#top"> <!-- CREST PLACEHOLDER — replace with the college's official crest --> ''' + CREST + ''' <span class="t">La Retraite<small data-en="Catholic Bilingual College · Yaoundé" data-fr="Collège catholique bilingue · Yaoundé">Collège catholique bilingue · Yaoundé</small></span></a><nav class="nav-links"><a href="#school" data-en="The School" data-fr="L'École">L'École</a><a href="#program" data-en="Program" data-fr="Programme">Programme</a><a href="#admissions" data-en="Admissions" data-fr="Admissions">Admissions</a><a href="#distinctions" data-en="Distinctions" data-fr="Distinctions">Distinctions</a></nav><a class="btn btn-gold" href="tel:+237693240047" data-en="Call the College" data-fr="Appeler le collège">Appeler le collège</a></div></header>
<!-- HERO -->
<div class="hero" id="top"><div class="wrap hero-grid"><div>
<span class="kicker" data-en="Yaoundé · Konrad Adenauer Avenue · Since 1950" data-fr="Yaoundé · Avenue Konrad Adenauer · Depuis 1950">Yaoundé · Avenue Konrad Adenauer · Depuis 1950</span>
<h1><span data-en="Forming the whole person," data-fr="Former l'homme,">Former l'homme,</span> <em data-en="according to God's plan." data-fr="selon le plan de Dieu.">selon le plan de Dieu.</em></h1>
<p class="sub" data-en="A Catholic bilingual college of the Archdiocese of Yaoundé. Founded in 1950 by the Sisters of the Holy Spirit and run by the Sisters of La Retraite since 1960, it welcomes boys and girls of every religious affiliation, in respect of its Catholic identity." data-fr="Collège catholique bilingue de l'Archidiocèse de Yaoundé. Fondé en 1950 par les Sœurs du Saint-Esprit et confié aux Sœurs de la Retraite en 1960, il accueille des élèves des deux sexes, de toute obédience religieuse, dans le respect de sa catholicité.">Collège catholique bilingue de l'Archidiocèse de Yaoundé. Fondé en 1950 par les Sœurs du Saint-Esprit et confié aux Sœurs de la Retraite en 1960, il accueille des élèves des deux sexes, de toute obédience religieuse, dans le respect de sa catholicité.</p>
<p style="font-style:italic;color:#F2C879;margin-top:10px;font-size:14.5px" data-en="&laquo; Régina Mundi Ora Pro Nobis &raquo; — the college motto" data-fr="« Régina Mundi Ora Pro Nobis » — devise du collège">« Régina Mundi Ora Pro Nobis » — devise du collège</p>
<div class="hero-ctas"><a class="btn btn-gold" href="tel:+237693240047" data-en="Book a Visit" data-fr="Prendre rendez-vous">Prendre rendez-vous</a><a class="btn btn-ghost" href="#program" data-en="Explore the Program" data-fr="Découvrir le programme">Découvrir le programme</a></div>
<div class="trust-row"><span data-en="1950 · Founded by the Sisters of the Holy Spirit" data-fr="1950 · Fondé par les Sœurs du Saint-Esprit">1950 · Fondé par les Sœurs du Saint-Esprit</span><span data-en="1960 · The Sisters of La Retraite" data-fr="1960 · Les Sœurs de la Retraite">1960 · Les Sœurs de la Retraite</span><span data-en="Bilingual · FR|EN" data-fr="Bilingue · FR|EN">Bilingue · FR|EN</span></div>
</div>
<div><div class="video-frame"><div class="video-inner">
<img src="data:image/jpeg;base64,''' + B64 + '''" alt="Semaine des Laureats 2026 — College de la Retraite" style="position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:top">
<div style="position:absolute;left:0;right:0;bottom:0;padding:34px 14px 12px;background:linear-gradient(transparent,rgba(11,27,62,.92))"><span class="video-cap" data-en="Semaine des Lauréats 2026 — your 10–15 photos take this place at kickoff" data-fr="Semaine des Lauréats 2026 — vos 10–15 photos prendront cette place à la réunion de lancement" style="color:#fff;display:block">Semaine des Lauréats 2026 — vos 10–15 photos prendront cette place à la réunion de lancement</span></div>
</div></div></div></div></div>
<!-- DUAL HUB -->
<section style="padding-top:64px"><div class="wrap"><div class="center"><span class="kicker" data-en="Quick access" data-fr="Accès rapide">Accès rapide</span><h2 data-en="What Do You Need Today?" data-fr="De Quoi Avez-Vous Besoin Aujourd'hui ?">De Quoi Avez-Vous Besoin Aujourd'hui ?</h2></div>
<div class="hub"><div class="hub-card h1c"><h3><span class="hi"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#F2C879" stroke-width="2"><path d="M12 3l8 4.5v9L12 21l-8-4.5v-9L12 3zM12 12l8-4.5M12 12v9M12 12L4 7.5"/></svg></span><span data-en="Prospective Families" data-fr="Familles candidates">Familles candidates</span></h3><ul><li><a href="#admissions"><span data-en="How to apply" data-fr="Comment s'inscrire">Comment s'inscrire</span><span>→</span></a></li><li><a href="#admissions"><span data-en="Fees & requirements" data-fr="Frais & conditions">Frais & conditions</span><span>→</span></a></li><li><a href="#admissions"><span data-en="Visit the college" data-fr="Visiter le collège">Visiter le collège</span><span>→</span></a></li><li><a href="#distinctions"><span data-en="Results & distinctions" data-fr="Résultats & distinctions">Résultats & distinctions</span><span>→</span></a></li></ul><p class="util" data-en="Utility pages go live with your site — updated by your admin in minutes." data-fr="Les pages pratiques sont en ligne avec votre site — mises à jour par votre administrateur en minutes.">Les pages pratiques sont en ligne avec votre site — mises à jour par votre administrateur en minutes.</p></div>
<div class="hub-card h2c"><h3><span class="hi"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#16337E" stroke-width="2"><rect x="3" y="4" width="18" height="17" rx="2"/><path d="M3 9h18M8 2v4M16 2v4"/></svg></span><span data-en="Current Families" data-fr="Familles inscrites">Familles inscrites</span></h3><ul><li><a href="#"><span data-en="School calendar" data-fr="Calendrier scolaire">Calendrier scolaire</span><span>→</span></a></li><li><a href="#"><span data-en="Announcements" data-fr="Annonces">Annonces</span><span>→</span></a></li><li><a href="#"><span data-en="E-learning portal" data-fr="Portail e-learning">Portail e-learning</span><span>→</span></a></li><li><a href="#"><span data-en="Virtual campus login" data-fr="Connexion au campus virtuel">Connexion au campus virtuel</span><span>→</span></a></li></ul></div></div>
</div></section>
<!-- WHY -->
<section id="school"><div class="wrap"><div class="center"><span class="kicker" data-en="Why La Retraite" data-fr="Pourquoi La Retraite">Pourquoi La Retraite</span><h2 data-en="A Complete Formation of the Person" data-fr="Une Formation Complète de la Personne">Une Formation Complète de la Personne</h2></div>
<div class="pillars"><div class="pil"><div class="ico"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#16337E" stroke-width="2"><path d="M12 2v8M8 6h8"/></svg></div><h3 data-en="Faith & Values" data-fr="Foi & Valeurs">Foi & Valeurs</h3><p data-en="A Catholic foundation since 1950, carried by the Sisters of La Retraite — a community that welcomes every religious affiliation in respect of its Catholic identity." data-fr="Un ancrage catholique depuis 1950, porté par les Sœurs de la Retraite — une communauté qui accueille toute obédience religieuse dans le respect de sa catholicité.">Un ancrage catholique depuis 1950, porté par les Sœurs de la Retraite — une communauté qui accueille toute obédience religieuse dans le respect de sa catholicité.</p></div>
<div class="pil"><div class="ico"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#16337E" stroke-width="2"><path d="M4 19h16M6 19V9l6-4 6 4v10"/></svg></div><h3 data-en="Discipline – Study – Charity" data-fr="Discipline – Étude – Charité">Discipline – Étude – Charité</h3><p data-en="Our motto, lived daily: schedules kept, serious work and charity toward every pupil, Monday to Saturday." data-fr="Notre devise, vécue au quotidien : des horaires tenus, un travail sérieux et la charité envers chaque élève, du lundi au samedi.">Notre devise, vécue au quotidien : des horaires tenus, un travail sérieux et la charité envers chaque élève, du lundi au samedi.</p></div>
<div class="pil"><div class="ico"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#16337E" stroke-width="2"><path d="M4 5h16v14H4z M4 12h16"/></svg></div><h3 data-en="Bilingual FR|EN" data-fr="Bilingue FR|EN">Bilingue FR|EN</h3><p data-en="A Catholic bilingual education — French and English as tools of learning and of the road to university." data-fr="Un enseignement catholique bilingue — français et anglais comme outils d'apprentissage et de la route vers l'université.">Un enseignement catholique bilingue — français et anglais comme outils d'apprentissage et de la route vers l'université.</p></div>
<div class="pil"><div class="ico"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#16337E" stroke-width="2"><path d="M12 2l2.5 6.5L21 9l-5 4.5L17.5 21 12 17l-5.5 4L8 13.5 3 9l6.5-.5z"/></svg></div><h3 data-en="School Life & Modernity" data-fr="Vie Scolaire & Modernité">Vie Scolaire & Modernité</h3><p data-en="E-learning portal, multimedia library, equipped classrooms — and a Semaine des Lauréats that celebrates excellence every year." data-fr="Portail e-learning, bibliothèque multimédia, salles équipées — et une Semaine des Lauréats qui célèbre l'excellence chaque année.">Portail e-learning, bibliothèque multimédia, salles équipées — et une Semaine des Lauréats qui célèbre l'excellence chaque année.</p></div></div>
</div></section>
<!-- ACADEMICS TABS -->
<!-- STAGE NAMES & QUOTES: VERIFY WITH THE COLLEGE BEFORE SENDING -->
<section id="program"><div class="wrap"><div class="center"><span class="kicker" data-en="Academics" data-fr="Programme">Programme</span><h2 data-en="Education by Stage" data-fr="L'Enseignement par Cycle">L'Enseignement par Cycle</h2></div>
<div class="tabs"><div class="tab-bar"><button class="tab-btn on" data-tab="t1" data-en="Forms 6–3 · Lower Secondary" data-fr="6e – 3e · Secondaire inférieur">6e – 3e · Secondaire inférieur</button><button class="tab-btn" data-tab="t2" data-en="Forms 2–1 · Upper Secondary" data-fr="2nde – 1ère · Secondaire supérieur">2nde – 1ère · Secondaire supérieur</button><button class="tab-btn" data-tab="t3" data-en="Final Year · GCE A-Level" data-fr="Terminale · GCE A-Level">Terminale · GCE A-Level</button></div>
<div class="tab-pane on" id="t1"><div><div class="meta-chips"><span class="mchip" data-en="Bilingual · FR|EN" data-fr="Bilingue · FR|EN">Bilingue · FR|EN</span></div><ul><li data-en="Strong foundations in French, mathematics, sciences and languages" data-fr="Des fondations solides en français, mathématiques, sciences et langues">Des fondations solides en français, mathématiques, sciences et langues</li><li data-en="BEPC preparation with individual follow-up" data-fr="Préparation au BEPC avec suivi individuel">Préparation au BEPC avec suivi individuel</li><li data-en="Moral education, prayer and class life" data-fr="Éducation morale, prière et vie de classe">Éducation morale, prière et vie de classe</li><li data-en="Careers day and the 'return to the sources' tradition" data-fr="Journée des métiers et tradition du « retour aux sources »">Journée des métiers et tradition du « retour aux sources »</li></ul></div><div class="quote" data-en="My child knows why they go to college every morning. That is all I ask." data-fr="Mon enfant sait pourquoi il va au collège chaque matin. C'est tout ce que je demande.">Mon enfant sait pourquoi il va au collège chaque matin. C'est tout ce que je demande.<b data-en="Parent, Form 4" data-fr="Parent, 4e">Parent, 4e</b></div></div>
<div class="tab-pane" id="t2"><div><div class="meta-chips"><span class="mchip" data-en="GCE O-Level (OBC)" data-fr="GCE O-Level (OBC)">GCE O-Level (OBC)</span></div><ul><li data-en="Science and arts classes" data-fr="Classes de sciences et de lettres">Classes de sciences et de lettres</li><li data-en="Intensive GCE O-Level (OBC) preparation" data-fr="Préparation intensive à la GCE O-Level (OBC)">Préparation intensive à la GCE O-Level (OBC)</li><li data-en="Practical work and regular mock examinations" data-fr="Travaux pratiques et examens blancs réguliers">Travaux pratiques et examens blancs réguliers</li><li data-en="Results published the same day as the examination" data-fr="Résultats publiés le jour même de l'épreuve">Résultats publiés le jour même de l'épreuve</li></ul></div><div class="quote" data-en="The results are posted the very same day. That transparency reassures parents." data-fr="Les résultats tombent la journée même. Cette transparence rassure les parents.">Les résultats tombent la journée même. Cette transparence rassure les parents.<b data-en="Parent, Form 1" data-fr="Parent, 1ère">Parent, 1ère</b></div></div>
<div class="tab-pane" id="t3"><div><div class="meta-chips"><span class="mchip" data-en="GCE A-Level" data-fr="GCE A-Level">GCE A-Level</span></div><ul><li data-en="A-Level preparation with personal follow-up" data-fr="Préparation aux A-Level avec accompagnement personnalisé">Préparation aux A-Level avec accompagnement personnalisé</li><li data-en="Guidance for university and career paths" data-fr="Orientation et conseil pour la suite des études">Orientation et conseil pour la suite des études</li><li data-en="Character file: commitments, distinctions, leadership" data-fr="Dossier de caractère : engagements, distinctions, leadership">Dossier de caractère : engagements, distinctions, leadership</li></ul></div><div class="quote" data-en="Finishing at La Retraite means entering a family that does not let you fall." data-fr="Terminer à La Retraite, c'est entrer dans une famille qui ne vous laisse pas tomber.">Terminer à La Retraite, c'est entrer dans une famille qui ne vous laisse pas tomber.<b data-en="Parent, Final Year" data-fr="Parent, Terminale">Parent, Terminale</b></div></div>
</div></div></section>
<!-- DISTINCTIONS -->
<section id="distinctions"><div class="wrap"><div class="center"><span class="kicker" data-en="Distinctions" data-fr="Distinctions">Distinctions</span><h2 data-en="A History of Educational Service" data-fr="Une Histoire de Service Éducatif">Une Histoire de Service Éducatif</h2></div>
<div class="aw-grid"><div class="aw"><div class="yr">1950</div><p data-en="Founded by the Sisters of the Holy Spirit — as the College du Saint-Esprit" data-fr="Fondation par les Sœurs du Saint-Esprit — le Collège du Saint-Esprit">Fondation par les Sœurs du Saint-Esprit — le Collège du Saint-Esprit</p></div>
<div class="aw"><div class="yr">1960</div><p data-en="Placed in the hands of the Sisters of La Retraite" data-fr="Le collège confié aux Sœurs de la Retraite">Le collège confié aux Sœurs de la Retraite</p></div>
<div class="aw"><div class="yr">76</div><p data-en="Years of educating in Yaoundé" data-fr="Années d'éducation à Yaoundé">Années d'éducation à Yaoundé</p></div>
<div class="aw"><div class="yr">2026</div><p data-en="Semaine des Lauréats — sports day, White Festival, ceremony" data-fr="Semaine des Lauréats — sport, White Festival, cérémonie">Semaine des Lauréats — sport, White Festival, cérémonie</p></div></div>
</div></section>
<!-- ADMISSIONS -->
<section id="admissions" style="background:#fff"><div class="wrap"><div class="center"><span class="kicker" data-en="Admissions" data-fr="Admissions">Admissions</span><h2 data-en="Three Steps to Join La Retraite" data-fr="Trois Étapes pour Rejoindre La Retraite">Trois Étapes pour Rejoindre La Retraite</h2></div>
<div class="steps"><div class="step"><div class="n">1</div><h3 data-en="Call the college" data-fr="Appeler le collège">Appeler le collège</h3><p data-en="One call to the administration — 693 240 047. Dates, file, fees: everything explained in a single call." data-fr="Un appel à l'administration — 693 240 047. Dates, dossier, frais : tout s'explique en un seul appel.">Un appel à l'administration — 693 240 047. Dates, dossier, frais : tout s'explique en un seul appel.</p></div>
<div class="step"><div class="n">2</div><h3 data-en="Visit the college" data-fr="Visiter le collège">Visiter le collège</h3><p data-en="See the classrooms, the multimedia library, meet the sisters and the teachers. The best way to know the school." data-fr="Voir les classes, la bibliothèque multimédia, rencontrer les sœurs et les enseignants. La meilleure façon de connaître l'école.">Voir les classes, la bibliothèque multimédia, rencontrer les sœurs et les enseignants. La meilleure façon de connaître l'école.</p></div>
<div class="step"><div class="n">3</div><h3 data-en="Enrol" data-fr="S'inscrire">S'inscrire</h3><p data-en="Submit the file; a light placement assessment finds the right class. Welcome to La Retraite." data-fr="Déposer le dossier ; une évaluation de niveau place votre enfant dans la bonne classe. Bienvenue à La Retraite.">Déposer le dossier ; une évaluation de niveau place votre enfant dans la bonne classe. Bienvenue à La Retraite.</p></div></div>
<div class="center" style="margin-top:36px"><a class="btn btn-gold" href="tel:+237693240047" data-en="Call 693 240 047 →" data-fr="Appeler le 693 240 047 →">Appeler le 693 240 047 →</a></div></div></section>
<!-- FAQ -->
<section><div class="wrap"><div class="center"><span class="kicker" data-en="FAQ" data-fr="FAQ">FAQ</span><h2 data-en="Questions Parents Ask" data-fr="Les Questions des Parents">Les Questions des Parents</h2></div>
<div class="faq"><details><summary data-en="Does the school accept pupils of every religion?" data-fr="L'école accepte-t-elle les élèves de toute religion ?">L'école accepte-t-elle les élèves de toute religion ?</summary><div class="ans" data-en="Yes — the college is a 'polyvalent' institution that welcomes boys and girls of every religious affiliation, on the condition that they accept and respect its Catholic identity." data-fr="Oui — le collège est un établissement polyvalent qui accueille les élèves des deux sexes et de toute obédience religieuse, à la condition d'accepter et de respecter sa catholicité.">Oui — le collège est un établissement polyvalent qui accueille les élèves des deux sexes et de toute obédience religieuse, à la condition d'accepter et de respecter sa catholicité.</div></details>
<details><summary data-en="Is the teaching bilingual?" data-fr="L'enseignement est-il bilingue ?">L'enseignement est-il bilingue ?</summary><div class="ans" data-en="Yes — it is a Catholic bilingual college. The administration confirms with families how subjects are distributed between French and English." data-fr="Oui — c'est un collège catholique bilingue. L'administration précise avec les familles la répartition des matières en français et en anglais.">Oui — c'est un collège catholique bilingue. L'administration précise avec les familles la répartition des matières en français et en anglais.</div></details>
<details><summary data-en="What are the class hours?" data-fr="Quels sont les horaires de la classe ?">Quels sont les horaires de la classe ?</summary><div class="ans" data-en="Classes run Monday to Saturday, and the college also operates an e-learning portal (virtual campus) for enrolled families." data-fr="Les cours se tiennent du lundi au samedi ; le collège dispose aussi d'un portail e-learning (campus virtuel) accessible aux familles inscrites.">Les cours se tiennent du lundi au samedi ; le collège dispose aussi d'un portail e-learning (campus virtuel) accessible aux familles inscrites.</div></details>
<details><summary data-en="How do I find out about fees?" data-fr="Comment connaître les frais de scolarité ?">Comment connaître les frais de scolarité ?</summary><div class="ans" data-en="The fee schedule for the current year is given by the administration — one call to 693 240 047 gives the full grid." data-fr="Le barème des frais est communiqué par l'administration — un appel au 693 240 047 donne la grille complète pour l'année en cours.">Le barème des frais est communiqué par l'administration — un appel au 693 240 047 donne la grille complète pour l'année en cours.</div></details></div>
</div></section>
<!-- FINAL CTA + FORM -->
<section class="final" id="visit"><div class="wrap"><span class="kicker" data-en="Admissions" data-fr="Admissions">Admissions</span>
<h2 style="color:#fff" data-en="Write Your Child's Story at La Retraite." data-fr="Écrivez l'Histoire de Votre Enfant à La Retraite.">Écrivez l'Histoire de Votre Enfant à La Retraite.</h2>
<p class="sub" data-en="Call, visit, or send the form — the administration replies." data-fr="Appelez, visitez, ou envoyez le formulaire — l'administration répond.">Appelez, visitez, ou envoyez le formulaire — l'administration répond.</p>
<div class="final-grid"><div class="pts">
<div class="pt"><span class="b">1</span><p data-en="<b>Admissions for 2026/2027</b> are handled directly with the administration — the sooner you call, the sooner you are placed." data-fr="<b>Les inscriptions 2026/2027</b> se traitent directement avec l'administration — plus vous appelez tôt, plus la place est assurée."><b>Les inscriptions 2026/2027</b> se traitent directement avec l'administration — plus vous appelez tôt, plus la place est assurée.</p></div>
<div class="pt"><span class="b">2</span><p data-en="<b>The college welcomes visiting families</b> — see the classrooms before you decide." data-fr="<b>Le collège accueille les familles en visite</b> — voir les classes avant de décider."><b>Le collège accueille les familles en visite</b> — voir les classes avant de décider.</p></div>
<div class="pt"><span class="b">3</span><p data-en="<b>One number answers:</b> 693 240 047 — admissions, fees, visits, everything." data-fr="<b>Un seul numéro répond :</b> 693 240 047 — inscriptions, frais, visite, tout."><b>Un seul numéro répond :</b> 693 240 047 — inscriptions, frais, visite, tout.</p></div></div>
<!-- DEMO: routes to the college's mobile. Activate a WhatsApp Business number and this becomes a live admissions inbox -->
<form class="form-card" onsubmit="return sendLead(event)"><h3 data-en="Request Admissions Information" data-fr="Demander des Informations d'Inscription">Demander des Informations d'Inscription</h3><p class="fc-sub" data-en="Sent on WhatsApp — 60 seconds, no email needed." data-fr="Envoyé sur WhatsApp — 60 secondes, pas d'e-mail nécessaire.">Envoyé sur WhatsApp — 60 secondes, pas d'e-mail nécessaire.</p>
<div class="fgrid"><div class="fld"><label data-en="Parent first name *" data-fr="Prénom du parent *">Prénom du parent *</label><input type="text" id="l-fn" required></div><div class="fld"><label data-en="Last name" data-fr="Nom">Nom</label><input type="text" id="l-ln"></div><div class="fld"><label data-en="Phone (WhatsApp) *" data-fr="Téléphone (WhatsApp) *">Téléphone (WhatsApp) *</label><input type="tel" id="l-ph" required></div><div class="fld"><label data-en="Child's class entering" data-fr="Classe d'entrée de l'enfant">Classe d'entrée de l'enfant</label><select id="l-gr"><option data-en="Form 6" data-fr="6e">6e</option><option data-en="Form 2" data-fr="2nde">2nde</option><option data-en="Final Year" data-fr="Terminale">Terminale</option><option data-en="Other" data-fr="Autre">Autre</option></select></div>
<div class="fld full"><label data-en="Question (optional)" data-fr="Question (facultatif)">Question (facultatif)</label><input type="text" id="l-q" placeholder="Frais ? Visite ?"></div></div>
<button type="submit" class="btn btn-gold" data-en="Send to the College →" data-fr="Envoyer au collège →">Envoyer au collège →</button>
<p class="form-small" data-en="Routes to the college's WhatsApp number — activate WhatsApp Business and this button becomes your admissions inbox on day one." data-fr="Dirigé vers le numéro WhatsApp du collège — activez WhatsApp Business et ce bouton devient votre boîte d'admissions dès le premier jour.">Dirigé vers le numéro WhatsApp du collège — activez WhatsApp Business et ce bouton devient votre boîte d'admissions dès le premier jour.</p></form></div></div></section>
<!-- FOOTER -->
<footer><div class="wrap"><div class="amk-bar"><span class="t"><b data-en="This website is a concept by AMK" data-fr="Ce site est une maquette par AMK">Ce site est une maquette par AMK</b> — Web Development &amp; Digital Solutions<small data-en="Bilingual (EN|FR), mobile-first, SEO-ready. Replace the crest, photos and figures with the college's own — and it's yours in 3–5 days." data-fr="Bilingue (FR|EN), mobile d'abord, prêt pour le SEO. Remplacez les armoiries, photos et chiffres par ceux du collège — et c'est à vous en 3–5 jours.">Bilingue (FR|EN), mobile d'abord, prêt pour le SEO. Remplacez les armoiries, photos et chiffres par ceux du collège — et c'est à vous en 3–5 jours.</small></span></div>
<div class="f-grid"><div><div style="display:flex;align-items:center;gap:10px;margin-bottom:12px">''' + CREST_FOOT + '''<span style="color:#fff;font-family:Georgia,serif;font-weight:700;font-size:16px">La Retraite</span></div>
<p data-en="La Retraite, Yaoundé · Archdiocese of Yaoundé · Cameroon" data-fr="La Retraite, Yaoundé · Archidiocèse de Yaoundé · Cameroun">La Retraite, Yaoundé · Archidiocèse de Yaoundé · Cameroun</p>
<p><a href="tel:+237693240047">+237 693 240 047</a></p>
<div class="map-ph" data-en="📍 Google Maps embed goes here" data-fr="📍 L'intégration Google Maps prend place ici">📍 L'intégration Google Maps prend place ici</div></div>
<div><h5 data-en="Quick Links" data-fr="Liens rapides">Liens rapides</h5><a href="#school" data-en="The School" data-fr="L'École">L'École</a><a href="#program" data-en="Program" data-fr="Programme">Programme</a><a href="#admissions" data-en="Admissions" data-fr="Admissions">Admissions</a><a href="#distinctions" data-en="Distinctions" data-fr="Distinctions">Distinctions</a></div>
<div><h5 data-en="Contact" data-fr="Contact">Contact</h5><p data-en="Administration — 693 240 047" data-fr="Administration — 693 240 047">Administration — 693 240 047</p><p data-en="Avenue Konrad Adenauer, Yaoundé — B.P. 159" data-fr="Avenue Konrad Adenauer, Yaoundé — B.P. 159">Avenue Konrad Adenauer, Yaoundé — B.P. 159</p><p style="font-size:12.5px;margin-top:8px" data-en="Concept page: crest, photos and figures are placeholders to be replaced with the college's own. Historical facts, mottoes, events and the mobile number cited are verified from the college's own website and 2026 publications." data-fr="Page concept : armoiries, photos et chiffres sont des emplacements à remplacer par ceux du collège. Les faits historiques, les devises, les événements et le numéro mobile cités sont vérifiés depuis le site du collège et ses publications 2026.">Page concept : armoiries, photos et chiffres sont des emplacements à remplacer par ceux du collège. Les faits historiques, les devises, les événements et le numéro mobile cités sont vérifiés depuis le site du collège et ses publications 2026.</p></div></div>
<div class="f-bottom"><span data-en="© 2026 College de la Retraite (concept)" data-fr="© 2026 Collège de la Retraite (concept)">© 2026 Collège de la Retraite (concept)</span><span data-en="Concept by AMK · Web Development & Digital Solutions" data-fr="Maquette par AMK · Développement Web & Solutions Digitales">Maquette par AMK · Développement Web & Solutions Digitales</span></div></div></footer>'''

head = ('<!DOCTYPE html>\n<html lang="fr">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n'
 '<title>Collège Catholique Bilingue La Retraite | Depuis 1950 à Yaoundé</title>\n'
 '<meta name="description" content="Collège catholique bilingue à Yaoundé depuis 1950 (Archidiocèse de Yaoundé). Discipline – Étude – Charité. E-learning, bibliothèque multimédia. Inscriptions — appelez le 693 240 047.">\n'
 '<script type="application/ld+json">{\n'
 '"@context": "https://schema.org", "@type": "EducationalOrganization",\n'
 '"name": "Collège Catholique Bilingue La Retraite",\n'
 '"alternateName": "La Retraite",\n'
 '"slogan": "Former l\'homme selon le plan de Dieu",\n'
 '"motto": "Régina Mundi Ora Pro Nobis — Discipline – Étude – Charité",\n'
 '"foundingDate": "1950",\n'
 '"address": { "@type": "PostalAddress", "streetAddress": "Avenue Konrad Adenauer, B.P. 159", "addressLocality": "Yaoundé", "addressCountry": "CM" },\n'
 '"telephone": "+237693240047",\n'
 '"description": "Collège catholique bilingue de l\'Archidiocèse de Yaoundé, fondé en 1950 par les Sœurs du Saint-Esprit, dirigé par les Sœurs de la Retraite depuis 1960."\n'
 '}</script>\n'
 f'<style>{style}</style>\n</head>\n<body>\n{BODY}\n<script>{script}</script>\n</body>\n</html>')

open(OUT, "w", encoding="utf-8").write(head)
en = len(re.findall(r'data-en="', head)); fr = len(re.findall(r'data-fr="', head))
print(f"built {OUT} · pairs {en}/{fr} · file {len(head)//1024}KB")
if en != fr:
    print("!! PAIR MISMATCH — check"); sys.exit(1)
