# -*- coding: utf-8 -*-
"""Build SAHISCOL concept (EN default) from the verified Sasse skeleton."""
import re, base64, sys

SASSE = "sjc-sasse-v2.html"
OUT = "concept-sahiscol-v1.html"
h = open(SASSE, encoding="utf-8").read()

style = h[h.find("<style>")+7 : h.find("</style>")]
script = h[h.rfind("<script>")+8 : h.rfind("</script>")]

# ---- palette remap (Sasse blues -> SAHISCOL plum/gold/cream)
MAP = {
 "#0F2456":"#38173D", "#17357F":"#4A2050", "#2E4E9E":"#4A2050",
 "#BFD0F5":"#E8C98A", "#C7D4F5":"#F0E2C8", "#EEF3FC":"#FAF1DC",
 "#F6F8FC":"#FAF6F1", "#DCE3F0":"#E6DACA", "#131A2A":"#241A26",
 "#54606F":"#5E5560", "#8C97A8":"#8E8493",
 "#0A1A3C":"#2A1230", "#93A3C4":"#C3AEC6", "#7E93BC":"#9E86A5",
 "#E3EAF8":"#F0E2C8",
 "rgba(46,78,158,.3)":"rgba(201,150,46,.30)",
 "rgba(201,162,39,.16)":"rgba(201,150,46,.16)",
}
for old, new in MAP.items():
    style = style.replace(old, new)
    script = script.replace(old, new)
style = style.replace(".btn-gold{background:var(--gold);color:#fff}", ".btn-gold{background:var(--gold);color:var(--brand)}")
style = style.replace("border-radius:50%;background:var(--gold);color:#fff", "border-radius:50%;background:var(--gold);color:var(--brand)}")
style = re.sub(r":root\{.*?\}", """:root{
  --brand:#4A2050; --brand2:#38173D; --brand3:#6B3570;
  --gold:#C9962E; --gold-l:#E8C98A; --gold-t:#FAF1DC;
  --bg:#FAF6F1; --white:#FFFFFF; --border:#E6DACA;
  --ink:#241A26; --slate:#5E5560; --slate-l:#8E8493;
}""", style, flags=re.S)

# ---- script: school name + WA number
script = script.replace('var WA_NUM = "237677195500"; // the college\'s number (activate WhatsApp Business to make the form live)',
 'var WA_NUM = "237677789631"; // DEMO: AMK\'s number — replace with the school\'s WhatsApp at kickoff')
script = script.replace('sjc-sasse-v2.html', 'concept-sahiscol-v1.html')
script = script.replace("Bonjour SJC Sasse !", "Bonjour Saint Anne's High School !")
script = script.replace("Hello SJC Sasse!", "Hello Saint Anne's High School!")

CREST = ('<svg viewBox="0 0 48 48"><path d="M24 3l17 6v13c0 10.5-7 18-17 23C14 40 7 32.5 7 22V9l17-6z" '
 'fill="#4A2050" stroke="#2A1230" stroke-width="2"/><path d="M24 10v14M18 16h12" stroke="#FFFFFF" stroke-width="3" '
 'stroke-linecap="round"/><path d="M14 32c4-2.5 7.5-2.5 10 0 2.5-2.5 6-2.5 10 0v7c-4-2.5-7.5-2.5-10 0-2.5-2.5-6-2.5-10 0v-7z" '
 'fill="#FFFFFF"/><path d="M24 32v7" stroke="#4A2050" stroke-width="1.3"/></svg>')
CREST_FOOT = ('<svg viewBox="0 0 48 48" width="38" height="38"><path d="M24 3l17 6v13c0 10.5-7 18-17 23C14 40 7 32.5 7 22V9l17-6z" '
 'fill="#38173D" stroke="#6B3570" stroke-width="2"/><path d="M24 10v14M18 16h12" stroke="#6B3570" stroke-width="3" '
 'stroke-linecap="round"/><path d="M14 32c4-2.5 7.5-2.5 10 0 2.5-2.5 6-2.5 10 0v7c-4-2.5-7.5-2.5-10 0-2.5-2.5-6-2.5-10 0v-7z" '
 'fill="#FAF6F1"/><path d="M24 32v7" stroke="#38173D" stroke-width="1.3"/></svg>')

BODY = '''<!-- TOP BAR -->
<div class="topbar"><div class="wrap"><span data-en="🎓 Admissions open — call 233 322 551" data-fr="🎓 Inscriptions ouvertes — appelez le 233 322 551">🎓 Admissions open — call 233 322 551</span> <span style="display:flex;align-items:center;gap:10px"> <a class="tb-portal" href="#" data-en="Portal Login →" data-fr="Connexion au portail →">Portal Login →</a> <span style="display:flex;border:1px solid var(--brand3);border-radius:99px;overflow:hidden"> <button id="btn-en" class="on" onclick="setLang('en')" style="background:var(--gold);color:var(--brand);border:none;font-size:12px;font-weight:800;padding:4px 12px;cursor:pointer">EN</button> <button id="btn-fr" onclick="setLang('fr')" style="background:transparent;color:#F0E2C8;border:none;font-size:12px;font-weight:800;padding:4px 12px;cursor:pointer">FR</button> </span> <a class="concept-chip" href="#">Website concept by <b>AMK</b></a> </span></div></div>
<!-- NAV -->
<header><div class="wrap nav"><a class="logo" href="#top"> <!-- CREST PLACEHOLDER — replace with the school's official crest --> ''' + CREST + ''' <span class="t">Saint Anne's<small data-en="High School · New Town, Limbe" data-fr="High School · New Town, Limbe">High School · New Town, Limbe</small></span></a><nav class="nav-links"><a href="#school" data-en="The School" data-fr="L'École">The School</a><a href="#streams" data-en="Streams" data-fr="Filières">Streams</a><a href="#admissions" data-en="Admissions" data-fr="Admissions">Admissions</a><a href="#standards" data-en="Standards" data-fr="Standards">Standards</a></nav><a class="btn btn-gold" href="tel:+237233322551" data-en="Call the School" data-fr="Appeler l'école">Call the School</a></div></header>
<!-- HERO -->
<div class="hero" id="top"><div class="wrap hero-grid"><div>
<span class="kicker" data-en="New Town, Limbe · Diocese of Buea" data-fr="New Town, Limbe · Diocèse de Buea">New Town, Limbe · Diocese of Buea</span>
<h1><span data-en="Beyond the classroom," data-fr="Au-delà de la classe,">Beyond the classroom,</span> <em data-en="talents are unleashed." data-fr="les talents s'épanouissent.">talents are unleashed.</em></h1>
<p class="sub" data-en="Saint Anne's High School is a Catholic school in New Town, Limbe — Grammar (Arts & Sciences) and Commercial (Marketing & Accounting) streams, taught Monday to Saturday in the Diocese of Buea." data-fr="Saint Anne's High School est une école catholique de New Town, Limbe — filières Grammar (Arts & Sciences) et Commercial (Marketing & Comptabilité), enseignées du lundi au samedi, dans le Diocèse de Buea.">Saint Anne's High School is a Catholic school in New Town, Limbe — Grammar (Arts & Sciences) and Commercial (Marketing & Accounting) streams, taught Monday to Saturday in the Diocese of Buea.</p>
<p style="font-style:italic;color:#E8C98A;margin-top:10px;font-size:14.5px" data-en="&ldquo;No child left behind — and no room for mediocrity.&rdquo; — the school's academic standard" data-fr="« Aucun enfant laissé derrière — et aucune place pour la médiocrité. » — le standard académique de l'école">&ldquo;No child left behind — and no room for mediocrity.&rdquo; — the school's academic standard</p>
<div class="hero-ctas"><a class="btn btn-gold" href="tel:+237233322551" data-en="Call the School" data-fr="Appeler l'école">Call the School</a><a class="btn btn-ghost" href="#streams" data-en="Explore the Streams" data-fr="Découvrir les filières">Explore the Streams</a></div>
<div class="trust-row"><span data-en="Grammar — Arts & Sciences" data-fr="Grammar — Arts & Sciences">Grammar — Arts & Sciences</span><span data-en="Commercial — Marketing & Accounting" data-fr="Commercial — Marketing & Comptabilité">Commercial — Marketing & Accounting</span><span data-en="Catholic · Diocese of Buea" data-fr="Catholique · Diocèse de Buea">Catholic · Diocese of Buea</span></div>
</div>
<div><div class="video-frame"><div class="video-inner">
<div class="play"></div>
<span class="video-cap" data-en="Campus life at Saint Anne's — your 10–15 photos take this place at kickoff" data-fr="La vie du campus à Saint Anne's — vos 10–15 photos prendront cette place à la réunion de lancement">Campus life at Saint Anne's — your 10–15 photos take this place at kickoff</span>
</div></div></div></div></div>
<!-- DUAL HUB -->
<section style="padding-top:64px"><div class="wrap"><div class="center"><span class="kicker" data-en="Quick access" data-fr="Accès rapide">Quick access</span><h2 data-en="What Do You Need Today?" data-fr="De Quoi Avez-Vous Besoin Aujourd'hui ?">What Do You Need Today?</h2></div>
<div class="hub"><div class="hub-card h1c"><h3><span class="hi"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#E8C98A" stroke-width="2"><path d="M12 3l8 4.5v9L12 21l-8-4.5v-9L12 3zM12 12l8-4.5M12 12v9M12 12L4 7.5"/></svg></span><span data-en="Prospective Parents" data-fr="Familles candidates">Prospective Parents</span></h3><ul><li><a href="#admissions"><span data-en="How to apply" data-fr="Comment s'inscrire">How to apply</span><span>→</span></a></li><li><a href="#admissions"><span data-en="Fees & requirements" data-fr="Frais & conditions">Fees & requirements</span><span>→</span></a></li><li><a href="#admissions"><span data-en="Visit the school" data-fr="Visiter l'école">Visit the school</span><span>→</span></a></li></ul><p class="util" data-en="Utility pages go live with your site — updated by your admin in minutes." data-fr="Les pages pratiques sont en ligne avec votre site — mises à jour par votre administrateur en minutes.">Utility pages go live with your site — updated by your admin in minutes.</p></div>
<div class="hub-card h2c"><h3><span class="hi"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#4A2050" stroke-width="2"><rect x="3" y="4" width="18" height="17" rx="2"/><path d="M3 9h18M8 2v4M16 2v4"/></svg></span><span data-en="Current Parents" data-fr="Familles inscrites">Current Parents</span></h3><ul><li><a href="#"><span data-en="School calendar" data-fr="Calendrier scolaire">School calendar</span><span>→</span></a></li><li><a href="#"><span data-en="Announcements" data-fr="Annonces">Announcements</span><span>→</span></a></li><li><a href="#"><span data-en="Results portal" data-fr="Portail des résultats">Results portal</span><span>→</span></a></li><li><a href="#"><span data-en="Portal login" data-fr="Connexion au portail">Portal login</span><span>→</span></a></li></ul></div></div>
</div></section>
<!-- WHY -->
<section id="school"><div class="wrap"><div class="center"><span class="kicker" data-en="Why Saint Anne's" data-fr="Pourquoi Saint Anne's">Why Saint Anne's</span><h2 data-en="A Standard That Is Lived" data-fr="Un Standard Qui Se Vit">A Standard That Is Lived</h2></div>
<div class="pillars"><div class="pil"><div class="ico"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#4A2050" stroke-width="2"><path d="M12 2l2.5 6.5L21 9l-5 4.5L17.5 21 12 17l-5.5 4L8 13.5 3 9l6.5-.5z"/></svg></div><h3 data-en="The Dean's Desk" data-fr="Le Bureau du Doyen">The Dean's Desk</h3><p data-en="After the first sequence, the cream of the class — 15+ averages, all papers passed — earn a special outing with the academic deans. Merit is a practice here, not a slogan." data-fr="Après la première séquence, la crème de la classe — moyennes de 15 et plus, toutes les matières réussies — gagne une sortie spéciale avec les doyens académiques. Le mérite est une pratique ici, pas un slogan.">After the first sequence, the cream of the class — 15+ averages, all papers passed — earn a special outing with the academic deans. Merit is a practice here, not a slogan.</p></div>
<div class="pil"><div class="ico"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#4A2050" stroke-width="2"><path d="M4 5h16v14H4z M4 12h16"/></svg></div><h3 data-en="Two Clear Streams" data-fr="Deux Filières Claires">Two Clear Streams</h3><p data-en="Grammar (Arts & Sciences) and Commercial (Marketing, Accounting) — a pathway chosen early and taught deeply." data-fr="Grammar (Arts & Sciences) et Commercial (Marketing, Comptabilité) — un chemin choisi tôt et enseigné en profondeur.">Grammar (Arts & Sciences) and Commercial (Marketing, Accounting) — a pathway chosen early and taught deeply.</p></div>
<div class="pil"><div class="ico"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#4A2050" stroke-width="2"><path d="M12 2v8M8 6h8"/></svg></div><h3 data-en="Faith & Formation" data-fr="Foi & Formation">Faith & Formation</h3><p data-en="A Catholic school in the Diocese of Buea — discipline, service and character formed alongside the curriculum." data-fr="Une école catholique du Diocèse de Buea — discipline, service et caractère formés avec le programme.">A Catholic school in the Diocese of Buea — discipline, service and character formed alongside the curriculum.</p></div>
<div class="pil"><div class="ico"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#4A2050" stroke-width="2"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 3"/></svg></div><h3 data-en="A Full School Week" data-fr="Une Semaine Scolaire Complète">A Full School Week</h3><p data-en="Classes run Monday to Saturday — 7:30 to 15:30 on week days, a half day on Saturday. A week that is taught, not rushed." data-fr="Les cours se tiennent du lundi au samedi — de 7h30 à 15h30 en semaine, une demi-journée le samedi. Une semaine enseignée, non bâclée.">Classes run Monday to Saturday — 7:30 to 15:30 on week days, a half day on Saturday. A week that is taught, not rushed.</p></div></div>
</div></section>
<!-- STREAMS TABS -->
<!-- STREAM DETAIL & QUOTES: VERIFY WITH THE SCHOOL BEFORE SENDING -->
<section id="streams"><div class="wrap"><div class="center"><span class="kicker" data-en="Academics" data-fr="Académique">Academics</span><h2 data-en="The Streams, Step by Step" data-fr="Les Filières, Étape par Étape">The Streams, Step by Step</h2></div>
<div class="tabs"><div class="tab-bar"><button class="tab-btn on" data-tab="t1" data-en="Forms 1–3 · Lower Secondary" data-fr="F1–3 · Secondaire inférieur">Forms 1–3 · Lower Secondary</button><button class="tab-btn" data-tab="t2" data-en="Forms 4–5 · GCE O-Level" data-fr="F4–5 · GCE O-Level">Forms 4–5 · GCE O-Level</button><button class="tab-btn" data-tab="t3" data-en="After O-Level · Progression" data-fr="Après l'O-Level · Progression">After O-Level · Progression</button></div>
<div class="tab-pane on" id="t1"><div><div class="meta-chips"><span class="mchip" data-en="Grammar & Commercial" data-fr="Grammar & Commercial">Grammar & Commercial</span></div><ul><li data-en="Strong foundations in English, mathematics and sciences" data-fr="De solides fondations en anglais, mathématiques et sciences">Strong foundations in English, mathematics and sciences</li><li data-en="First sequence: the dean's desk rewards the 15+ averages" data-fr="Première séquence : le bureau du doyen récompense les moyennes de 15 et plus">First sequence: the dean's desk rewards the 15+ averages</li><li data-en="Character formation: discipline, service, worship" data-fr="Formation du caractère : discipline, service, prière">Character formation: discipline, service, worship</li></ul></div><div class="quote" data-en="My daughter comes home proud — the standard is visible from the first sequence." data-fr="Ma fille rentre fière — le standard se voit dès la première séquence.">My daughter comes home proud — the standard is visible from the first sequence.<b data-en="Parent, Form 2" data-fr="Parent, F2">Parent, Form 2</b></div></div>
<div class="tab-pane" id="t2"><div><div class="meta-chips"><span class="mchip" data-en="GCE O-Level" data-fr="GCE O-Level">GCE O-Level</span></div><ul><li data-en="Grammar and Commercial streams side by side" data-fr="Les filières Grammar et Commercial côte à côte">Grammar and Commercial streams side by side</li><li data-en="Past-paper practice and regular mock examinations" data-fr="Entraînement sur sujets précédents et examens blancs réguliers">Past-paper practice and regular mock examinations</li><li data-en="Examination readiness in every subject" data-fr="Préparation aux examens dans toutes les matières">Examination readiness in every subject</li></ul></div><div class="quote" data-en="The O-Level board is the same for every stream — and the results speak." data-fr="Le jury O-Level est le même pour toutes les filières — et les résultats parlent.">The O-Level board is the same for every stream — and the results speak.<b data-en="Parent, Form 5" data-fr="Parent, F5">Parent, Form 5</b></div></div>
<div class="tab-pane" id="t3"><div><div class="meta-chips"><span class="mchip" data-en="Progression" data-fr="Progression">Progression</span></div><ul><li data-en="University and career guidance" data-fr="Orientation universitaire et professionnelle">University and career guidance</li><li data-en="A record built on the dean's desk standard" data-fr="Un dossier construit sur le standard du bureau du doyen">A record built on the dean's desk standard</li><li data-en="Strong O-Level results open the university doors" data-fr="De bons résultats O-Level ouvrent les portes de l'université">Strong O-Level results open the university doors</li></ul></div><div class="quote" data-en="Three years in, the difference is in the habit of work." data-fr="Après trois ans, la différence est dans l'habitude du travail.">Three years in, the difference is in the habit of work.<b data-en="Parent" data-fr="Parent">Parent</b></div></div>
</div></div></section>
<!-- STANDARDS -->
<section id="standards"><div class="wrap"><div class="center"><span class="kicker" data-en="Standards" data-fr="Standards">Standards</span><h2 data-en="A Story of Standards" data-fr="Une Histoire de Standards">A Story of Standards</h2></div>
<div class="aw-grid"><div class="aw"><div class="yr">15+</div><p data-en="Dean's-desk average — all papers passed" data-fr="Moyenne du bureau du doyen — toutes les matières réussies">Dean's-desk average — all papers passed</p></div>
<div class="aw"><div class="yr">2</div><p data-en="Streams — Grammar (Arts & Sciences) and Commercial" data-fr="Filières — Grammar (Arts & Sciences) et Commercial">Streams — Grammar (Arts & Sciences) and Commercial</p></div>
<div class="aw"><div class="yr">6</div><p data-en="Days a week of teaching, Monday to Saturday" data-fr="Jours de cours par semaine, du lundi au samedi">Days a week of teaching, Monday to Saturday</p></div>
<div class="aw"><div class="yr">1</div><p data-en="Standard — no room for mediocrity" data-fr="Standard — aucune place pour la médiocrité">Standard — no room for mediocrity</p></div></div>
</div></section>
<!-- ADMISSIONS -->
<section id="admissions" style="background:#fff"><div class="wrap"><div class="center"><span class="kicker" data-en="Admissions" data-fr="Admissions">Admissions</span><h2 data-en="Three Steps to Join Saint Anne's" data-fr="Trois Étapes pour Rejoindre Saint Anne's">Three Steps to Join Saint Anne's</h2></div>
<div class="steps"><div class="step"><div class="n">1</div><h3 data-en="Call the office" data-fr="Appeler le secrétariat">Call the office</h3><p data-en="One call to 233 322 551 — dates, requirements and what to bring, explained in one conversation." data-fr="Un appel au 233 322 551 — dates, conditions et documents à apporter, expliqués en une seule conversation.">One call to 233 322 551 — dates, requirements and what to bring, explained in one conversation.</p></div>
<div class="step"><div class="n">2</div><h3 data-en="Visit New Town" data-fr="Visiter New Town">Visit New Town</h3><p data-en="Walk the campus, sit in a class, meet the staff. The best way to know a school." data-fr="Parcourez le campus, assistez à un cours, rencontrez le personnel. La meilleure façon de connaître une école.">Walk the campus, sit in a class, meet the staff. The best way to know a school.</p></div>
<div class="step"><div class="n">3</div><h3 data-en="Apply" data-fr="Candidater">Apply</h3><p data-en="Submit the file; a light placement assessment finds the right class. Welcome to Saint Anne's." data-fr="Déposez le dossier ; une évaluation d'orientation légère trouve la bonne classe. Bienvenue à Saint Anne's.">Submit the file; a light placement assessment finds the right class. Welcome to Saint Anne's.</p></div></div>
<div class="center" style="margin-top:36px"><a class="btn btn-gold" href="tel:+237233322551" data-en="Call 233 322 551 →" data-fr="Appeler le 233 322 551 →">Call 233 322 551 →</a></div></div></section>
<!-- FAQ -->
<section><div class="wrap"><div class="center"><span class="kicker" data-en="FAQ" data-fr="FAQ">FAQ</span><h2 data-en="Questions Parents Ask" data-fr="Les Questions des Parents">Questions Parents Ask</h2></div>
<div class="faq"><details><summary data-en="What streams does the school offer?" data-fr="Quelles filières propose l'école ?">What streams does the school offer?</summary><div class="ans" data-en="Two — Grammar (Arts and Sciences) and Commercial (Marketing, Accounting). Both lead to the GCE O-Level." data-fr="Deux — Grammar (Arts et Sciences) et Commercial (Marketing, Comptabilité). Les deux mènent à la GCE O-Level.">Two — Grammar (Arts and Sciences) and Commercial (Marketing, Accounting). Both lead to the GCE O-Level.</div></details>
<details><summary data-en="What are the school hours?" data-fr="Quels sont les horaires de l'école ?">What are the school hours?</summary><div class="ans" data-en="Monday to Friday, 7:30 to 15:30; Saturday morning, 7:30 to 13:30. Sunday is closed." data-fr="Du lundi au vendredi, de 7h30 à 15h30 ; le samedi matin, de 7h30 à 13h30. Dimanche fermé.">Monday to Friday, 7:30 to 15:30; Saturday morning, 7:30 to 13:30. Sunday is closed.</div></details>
<details><summary data-en="How does the school support its best performers?" data-fr="Comment l'école soutient-elle ses meilleurs élèves ?">How does the school support its best performers?</summary><div class="ans" data-en="The dean's desk: after the first sequence, students with 15+ averages who pass all papers earn a special outing with the academic deans." data-fr="Le bureau du doyen : après la première séquence, les élèves avec des moyennes de 15 et plus qui réussissent toutes les matières gagnent une sortie spéciale avec les doyens académiques.">The dean's desk: after the first sequence, students with 15+ averages who pass all papers earn a special outing with the academic deans.</div></details>
<details><summary data-en="How do I find out about fees?" data-fr="Comment connaître les frais de scolarité ?">How do I find out about fees?</summary><div class="ans" data-en="The fee schedule for the current year is available at the office — one call to 233 322 551 gives the full breakdown." data-fr="Le barème des frais de l'année en cours est disponible au secrétariat — un appel au 233 322 551 donne le détail complet.">The fee schedule for the current year is available at the office — one call to 233 322 551 gives the full breakdown.</div></details></div>
</div></section>
<!-- FINAL CTA + FORM -->
<section class="final" id="visit"><div class="wrap"><span class="kicker" data-en="Admissions" data-fr="Admissions">Admissions</span>
<h2 style="color:#fff" data-en="Give Your Child the Standard." data-fr="Offrez à Votre Enfant ce Standard.">Give Your Child the Standard.</h2>
<p class="sub" data-en="Call, visit, or send the form — the office replies promptly." data-fr="Appelez, visitez, ou envoyez le formulaire — le secrétariat répond rapidement.">Call, visit, or send the form — the office replies promptly.</p>
<div class="final-grid"><div class="pts">
<div class="pt"><span class="b">1</span><p data-en="<b>Admissions are open</b> — the sooner you call, the sooner you are placed." data-fr="<b>Les inscriptions sont ouvertes</b> — plus vous appelez tôt, plus vous êtes placé tôt."><b>Admissions are open</b> — the sooner you call, the sooner you are placed.</p></div>
<div class="pt"><span class="b">2</span><p data-en="<b>The campus welcomes visiting families</b> — sit in a class before you decide." data-fr="<b>Le campus accueille les familles en visite</b> — assistez à un cours avant de décider."><b>The campus welcomes visiting families</b> — sit in a class before you decide.</p></div>
<div class="pt"><span class="b">3</span><p data-en="<b>One number answers:</b> 233 322 551 — admissions, fees, visits, everything." data-fr="<b>Un seul numéro répond :</b> 233 322 551 — admissions, frais, visite, tout."><b>One number answers:</b> 233 322 551 — admissions, fees, visits, everything.</p></div></div>
<!-- DEMO: routes to AMK's number until the school's WhatsApp is known. Activate a WhatsApp Business number and this becomes a live admissions inbox -->
<form class="form-card" onsubmit="return sendLead(event)"><h3 data-en="Request Admissions Information" data-fr="Demander des informations d'admission">Request Admissions Information</h3><p class="fc-sub" data-en="Sent on WhatsApp — 60 seconds, no email needed." data-fr="Envoyé sur WhatsApp — 60 secondes, pas d'e-mail nécessaire.">Sent on WhatsApp — 60 seconds, no email needed.</p>
<div class="fgrid"><div class="fld"><label data-en="Parent first name *" data-fr="Prénom du parent *">Parent first name *</label><input type="text" id="l-fn" required></div><div class="fld"><label data-en="Last name" data-fr="Nom">Last name</label><input type="text" id="l-ln"></div><div class="fld"><label data-en="Phone (WhatsApp) *" data-fr="Téléphone (WhatsApp) *">Phone (WhatsApp) *</label><input type="tel" id="l-ph" required></div><div class="fld"><label data-en="Child's class entering" data-fr="Classe d'entrée de l'enfant">Child's class entering</label><select id="l-gr"><option data-en="Form 1" data-fr="Forme 1">Form 1</option><option data-en="Form 4" data-fr="Forme 4">Form 4</option><option data-en="Other" data-fr="Autre">Other</option></select></div>
<div class="fld full"><label data-en="Question (optional)" data-fr="Question (facultatif)">Question (optional)</label><input type="text" id="l-q" placeholder="Fees? Streams?"></div></div>
<button type="submit" class="btn btn-gold" data-en="Send to the School →" data-fr="Envoyer à l'école →">Send to the School →</button>
<p class="form-small" data-en="Routes to the school's WhatsApp number — activate WhatsApp Business and this button becomes your admissions inbox on day one." data-fr="Dirigé vers le numéro WhatsApp de l'école — activez WhatsApp Business et ce bouton devient votre boîte d'admissions dès le premier jour.">Routes to the school's WhatsApp number — activate WhatsApp Business and this button becomes your admissions inbox on day one.</p></form></div></div></section>
<!-- FOOTER -->
<footer><div class="wrap"><div class="amk-bar"><span class="t"><b data-en="This website is a concept by AMK" data-fr="Ce site est une maquette par AMK">This website is a concept by AMK</b> — Web Development &amp; Digital Solutions<small data-en="Bilingual (EN|FR), mobile-first, SEO-ready. Replace the crest, photos and quotes with the school's own — and it's yours in 3–5 days." data-fr="Bilingue (EN|FR), mobile d'abord, prêt pour le SEO. Remplacez les armoiries, photos et citations par ceux de l'école — et c'est à vous en 3–5 jours.">Bilingual (EN|FR), mobile-first, SEO-ready. Replace the crest, photos and quotes with the school's own — and it's yours in 3–5 days.</small></span></div>
<div class="f-grid"><div><div style="display:flex;align-items:center;gap:10px;margin-bottom:12px">''' + CREST_FOOT + '''<span style="color:#fff;font-family:Georgia,serif;font-weight:700;font-size:16px">Saint Anne's</span></div>
<p data-en="New Town, Limbe · Diocese of Buea · Cameroon" data-fr="New Town, Limbe · Diocèse de Buea · Cameroun">New Town, Limbe · Diocese of Buea · Cameroon</p>
<p><a href="tel:+237233322551">+237 233 322 551</a></p>
<div class="map-ph" data-en="📍 Google Maps embed goes here" data-fr="📍 L'intégration Google Maps prend place ici">📍 Google Maps embed goes here</div></div>
<div><h5 data-en="Quick Links" data-fr="Liens rapides">Quick Links</h5><a href="#school" data-en="The School" data-fr="L'École">The School</a><a href="#streams" data-en="Streams" data-fr="Filières">Streams</a><a href="#admissions" data-en="Admissions" data-fr="Admissions">Admissions</a><a href="#standards" data-en="Standards" data-fr="Standards">Standards</a></div>
<div><h5 data-en="Contact" data-fr="Contact">Contact</h5><p data-en="Office — 233 322 551" data-fr="Secrétariat — 233 322 551">Office — 233 322 551</p><p data-en="info@sahiscol.org" data-fr="info@sahiscol.org">info@sahiscol.org</p><p style="font-size:12.5px;margin-top:8px" data-en="Concept page: crest, photos and quotes are placeholders to be replaced with the school's own. Facts cited (streams, hours, dean's desk standard, motto lines) are verified from the school's own website and the diocesan profile." data-fr="Page concept : armoiries, photos et citations sont des emplacements à remplacer par ceux de l'école. Les faits cités (filières, horaires, standard du bureau du doyen, devises) sont vérifiés depuis le site de l'école et le profil du diocèse.">Concept page: crest, photos and quotes are placeholders to be replaced with the school's own. Facts cited (streams, hours, dean's desk standard, motto lines) are verified from the school's own website and the diocesan profile.</p></div></div>
<div class="f-bottom"><span data-en="© 2026 Saint Anne's High School Limbe (concept)" data-fr="© 2026 Saint Anne's High School Limbe (concept)">© 2026 Saint Anne's High School Limbe (concept)</span><span data-en="Concept by AMK · Web Development & Digital Solutions" data-fr="Maquette par AMK · Développement Web & Solutions Digitales">Concept by AMK · Web Development & Digital Solutions</span></div></div></footer>'''

head = ('<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n'
 '<title>Saint Anne\'s High School Limbe | Catholic School · Grammar &amp; Commercial · New Town</title>\n'
 '<meta name="description" content="Saint Anne\'s High School Limbe — Catholic school, Grammar (Arts & Sciences) and Commercial (Marketing & Accounting) streams, New Town, Limbe. No room for mediocrity. Admissions: call 233 322 551.">\n'
 '<script type="application/ld+json">{\n'
 '"@context": "https://schema.org", "@type": "EducationalOrganization",\n'
 '"name": "Saint Anne\'s High School Limbe",\n'
 '"alternateName": "SAHISCOL",\n'
 '"slogan": "Beyond the classroom, talents are unleashed",\n'
 '"address": { "@type": "PostalAddress", "addressLocality": "New Town, Limbe", "addressCountry": "CM" },\n'
 '"telephone": "+237233322551",\n'
 '"description": "Catholic school in New Town, Limbe — Grammar and Commercial streams, Diocese of Buea."\n'
 '}</script>\n'
 f'<style>{style}</style>\n</head>\n<body>\n{BODY}\n<script>{script}</script>\n</body>\n</html>')

open(OUT, "w", encoding="utf-8").write(head)
en = len(re.findall(r'data-en="', head)); fr = len(re.findall(r'data-fr="', head))
print(f"built {OUT} · pairs {en}/{fr} · file {len(head)//1024}KB")
if en != fr:
    print("!! PAIR MISMATCH — check"); sys.exit(1)
